framework:
  workflows:
    demande:
      type: 'state_machine'
      audit_trail:
        enabled: true
      marking_store:
        type: 'method'
        property: 'etat'
      supports:
        - App\Entity\Demande
      initial_marking: demande_initie
      places:
        - demande_initie
        - demande_valider_directeur
        - demande_valider_president
        - demande_valider_attente_document
        - demande_valider
        - document_soumis_directeur
        - document_accepte
        - demande_refuser
      transitions:
        passer:
          from: demande_initie
          to: demande_valider_directeur
        accepatation_president:
          from: demande_valider_directeur
          to: demande_valider
        accepatation_president_attente_document:
          from: demande_valider_directeur
          to: demande_valider_attente_document
        document_enregister:
          from: demande_valider_attente_document
          to: document_soumis_directeur
        document_verification_accepte:
          from: document_soumis_directeur
          to: demande_valider
        document_verification_refuse:
          from: document_soumis_directeur
          to: demande_valider_attente_document
        demande_refuser:
          from: demande_initie
          to: demande_refuser
        demande_refuser_president:
          from: demande_valider_directeur
          to: demande_refuser

    demandeBrouillon:
      type: 'state_machine'
      audit_trail:
        enabled: true
      marking_store:
        type: 'method'
        property: 'etat'
      supports:
        - App\Entity\DemandeBrouillon
      initial_marking: brouillon_initie
      places:
        - brouillon_initie
        - brouillon_valider
        - brouillon_review_president
        - brouillon_rejeter
      transitions:
        passer:
          from: brouillon_initie
          to: brouillon_valider
        review_president:
          from: brouillon_initie
          to: brouillon_review_president
        rejeter_directeur:
          from: brouillon_initie
          to: brouillon_rejeter
        rejeter_president:
          from: brouillon_review_president
          to: brouillon_rejeter
        valider_president:
          from: brouillon_review_president
          to: brouillon_valider  
        

          